### ISSUE TITLE
Unable to connect to grbl

### ISSUE THREAD

**Issue by oilytin** [mstrens/Hot_wire#1]
Un able to connect to GRBL (previous version was ok)
Console displays the following text
`Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 926, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "fil_chaud.py", line 87, in execCmd
  File "fil_chaud_grbl.py", line 23, in connectToGrbl
  File "gerbil.py", line 412, in cnect
  File "gerbil_interface.py", line 65, in start
ValueError: Unknown format code 'd' for object of type 'str'`

**Comment by chrisbrent** [comment]
Look like a bad logging format, and all the other logging is commented. I made a PR to fix that here:
https://github.com/mstrens/Hot_wire/pull/2
You can pull that fork if you want a quick fix.

**Comment by oilytin** [comment]
Thanks chris! will have a look now.
Great work BTW just starting to get to grips with it.
Anthony

**Comment by chrisbrent** [comment]
Hi, this isn't my project but I'm going to use it too :)

**Comment by oilytin** [comment]
Has the exe been updated or would i have to compile it?

**Comment by chrisbrent** [comment]
You'd have to compile it, sorry I don't have a windows machine.
